FROM node:latest

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el package.json y package-lock.json para instalar las dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Construye el proyecto React
RUN npm run build

# Expone el puerto en el que se ejecutará el servidor de producción de React (por ejemplo, 3000)
EXPOSE 3000

# Comando para iniciar el servidor de producción de React
CMD ["npm", "start"]
