version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=your_root_password
      - DB_DATABASE=test
    depends_on:
      - mysql
    networks:
      - internal_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - internal_network

  mysql:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: test
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - internal_network
    command: ["--init-file", "/docker-entrypoint-initdb.d/init-db.sql"]

networks:
  internal_network:
    driver: bridge


# version: '3.9'

# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: backend
#     ports:
#       - "5000:5000"
#     environment:
#       - DB_HOST=mysql
#       - DB_USER=root
#       - DB_PASSWORD=your_root_password
#       - DB_DATABASE=test
#     depends_on:
#       - mysql
#     networks:
#       - internal_network

#   frontend:
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#     networks:
#       - internal_network

#   mysql:
#     image: mysql:latest
#     container_name: mysql_database
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: your_root_password
#       MYSQL_DATABASE: test
#       MYSQL_USER: root
#       MYSQL_PASSWORD: your_database_password
#     volumes:
#       - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
#     ports:
#       - "3306:3306"     # Puerto para el protocolo MySQL
#       - "33060:33060"   # Puerto para el protocolo MySQL X
#     networks:
#       - internal_network
#     command: ["--init-file", "/docker-entrypoint-initdb.d/init-db.sql"]  


# networks:
#   internal_network:
#     driver: bridge
